// <auto-generated />
namespace Consoledesafio01aula07.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Addalterar : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addalterar));
        
        string IMigrationMetadata.Id
        {
            get { return "202009060141589_Addalterar"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
